apiVersion: apps/v1 
kind: Deployment
metadata:
  name: kubernetes-demo-hello-app
  labels: 
     app: finbert-app

spec:
  replicas: 2 
  selector:
    matchLabels:
      app: finbert-app

  template:
    metadata:
      labels:
        app: finbert-app
    spec:
      containers:
      - name: hello-app
        image: DOCKER_IMAGE
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1