apiVersion: v1
kind: Service
metadata:
  name: finbert-app-service
  labels:
    app: finbert-app 
spec:
  selector:
    app: finbert-app 

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
